version: '3.7'

services:
    db:
      image: postgres:12
      environment:
        - POSTGRES_DB=mars
        - POSTGRES_USER=martian
        - POSTGRES_PASSWORD=thorgate
      volumes:
        - db-data:/var/lib/postgresql/data
    api:
      working_dir: /terra-mars-api
      build: ./terra-mars-api
      command: daphne -b 0.0.0.0 -p 8000 mars.asgi:application
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      depends_on:
        - db
    frontend:
        working_dir: /terra-mars-spa
        build: ./terra-mars-spa
        #volumes:
        #- .:/app
        ports:
         - "8080:80"
        depends_on:
            - api



volumes:
  db-data:
